on:
  workflow_dispatch:
  schedule:
    # GMT-3
    - cron: "30 16 * * *"

jobs:
  get_data:
    runs-on: ubuntu-20.04
    steps:
      - name: Get this repository
        uses: actions/checkout@v2
        with:
          path: clone
  
      - name: Get official repository
        uses: actions/checkout@v2
        with:
          repository: MinCiencia/Datos-COVID19
          path: official

      - name: Copy input files
        run: cp official/input clone -r -f

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
            python-version: 3.7

      - name: Install dependencies
        run: |
          cd clone
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate Products
        run: cd clone; bash src/make

      - name: Save files
        run: |
          cd clone
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "updated input files"
          git push
